/*
 */
package cz.dfi.graphs;

import cz.dfi.datamodel.FlightDataRecord;
import cz.dfi.recorddataprovider.caching.CachedDataProvider;
import cz.dfi.recorddataprovider.caching.CachedDataReceiver;
import java.awt.BorderLayout;
import java.util.List;
import java.util.Properties;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.DefaultXYDataset;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@TopComponent.Description(
        preferredID = "AltitudeGraphTopComponent",
        iconBase = "cz/dfi/graphs/height.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "output", openAtStartup = true)
@ActionID(category = "Window", id = "cz.dfi.graphs.AltitudeGraphTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_AltitudeGraphAction",
        preferredID = "AltitudeGraphTopComponent"
)
@Messages({
    "CTL_AltitudeGraphAction=AltitudeGraph",
    "CTL_AltitudeGraphTopComponent=AltitudeGraph Window",
    "HINT_AltitudeGraphTopComponent=This is a AltitudeGraph window"
})
public final class AltitudeGraphTopComponent extends TopComponent implements CachedDataReceiver<double[][]> {

    private CachedDataProvider<double[][]> cachedDataProvider;
    protected final JFreeChart chart;
    protected final DefaultXYDataset dataSet;

    public AltitudeGraphTopComponent() {
        initComponents();
        setName(Bundle.CTL_AltitudeGraphTopComponent());
        setToolTipText(Bundle.HINT_AltitudeGraphTopComponent());
        dataSet = new DefaultXYDataset();
        chart = ChartFactory.createXYLineChart(null,
                "Time [sec]", "Altitude [cm]", dataSet, PlotOrientation.VERTICAL, false, true,
                false);
        ChartPanel cp = new ChartPanel(chart);
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(cp);
        chart.getXYPlot().setDomainPannable(true);
        chart.getXYPlot().setRangePannable(true);
    }

    @Override
    public void componentOpened() {
        cachedDataProvider = CachedDataProvider.create(this);
    }

    @Override
    public void componentClosed() {
        cachedDataProvider.deleteData();
    }

    @Override
    protected void componentShowing() {
        super.componentShowing();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    @Override
    public double[][] getDataForStoring(Lookup currentContext) {
        List<FlightDataRecord> r = GraphsCommon.getFlightRecords(currentContext);
        graphValues = new double[2][r.size()];
        for (int i = 0; i < r.size(); i++) {
            FlightDataRecord rec = r.get(i);
            graphValues[0][i] = rec.droneTime / 1_000_000;
            graphValues[1][i] = rec.altitude / 10;
        }
        return graphValues;
    }

    private double[][] graphValues;

    @Override
    public void setCurrentData(double[][] data) {
        graphValues = data;
        dataSet.removeSeries("Altitude");
        if (data != null) {
            dataSet.addSeries("Altitude", data);
        }

    }

    void writeProperties(Properties p) {
    }

    void readProperties(Properties p) {
    }
}
