/*
 */
package cz.dfi.graphs;

import cz.dfi.datamodel.FlightDataRecord;
import cz.dfi.recorddataprovider.caching.CachedDataProvider;
import cz.dfi.recorddataprovider.caching.CachedDataReceiver;
import java.awt.BorderLayout;
import java.util.List;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.DefaultXYDataset;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//cz.dfi.graphs//BatteryGraph//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "BatteryGraphTopComponent",
        iconBase = "cz/dfi/graphs/iconmonstr-battery-7-icon-16.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "output", openAtStartup = true)
@ActionID(category = "Window", id = "cz.dfi.graphs.BatteryGraphTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_BatteryGraphAction",
        preferredID = "BatteryGraphTopComponent"
)
@Messages({
    "CTL_BatteryGraphAction=BatteryGraph",
    "CTL_BatteryGraphTopComponent=BatteryGraph Window",
    "HINT_BatteryGraphTopComponent=This is a BatteryGraph window"
})
public final class BatteryGraphTopComponent extends TopComponent implements CachedDataReceiver<double[][]> {
    private CachedDataProvider<double[][]> cachedDataProvider;
    protected final JFreeChart chart;
    protected final DefaultXYDataset dataSet;
    public BatteryGraphTopComponent() {
        initComponents();
        setName(Bundle.CTL_BatteryGraphTopComponent());
        setToolTipText(Bundle.HINT_BatteryGraphTopComponent());
        dataSet = new DefaultXYDataset();
        chart = ChartFactory.createXYLineChart(null,
                "Time [sec]", "Battery [percent]", dataSet, PlotOrientation.VERTICAL, false, true,
                false);
        ChartPanel cp = new ChartPanel(chart);
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(cp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
     @Override
    public void componentOpened() {
        cachedDataProvider = CachedDataProvider.create(this);
    }

    @Override
    public void componentClosed() {
        cachedDataProvider.deleteData();
    }

    @Override
    protected void componentShowing() {
        super.componentShowing();
    }
      @Override
    public double[][] getDataForStoring(Lookup currentContext) {
        List<FlightDataRecord> r = GraphsCommon.getFlightRecords(currentContext);
        graphValues = new double[2][r.size()];
        for (int i = 0; i < r.size(); i++) {
            FlightDataRecord rec = r.get(i);
            graphValues[0][i] = rec.droneTime / 1_000_000;
            graphValues[1][i] = rec.batteryPercent;
        }
        return graphValues;
    }

    private double[][] graphValues;

    @Override
    public void setCurrentData(double[][] data) {
        graphValues = data;
        dataSet.removeSeries("Battery");
        if (data != null) {
            dataSet.addSeries("Battery", data);
        }

    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
