/*
 */
package cz.dfi.graphs;

import cz.dfi.datamodel.common.BatteryPercentWrapper;
import cz.dfi.recorddataprovider.FileLookup;
import java.awt.BorderLayout;
import java.util.Collection;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays battery percentage graph.
 */
@TopComponent.Description(
        preferredID = "BatteryGraphTopComponent",
        iconBase = "cz/dfi/graphs/iconmonstr-battery-7-icon-16.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "output", openAtStartup = true)
@ActionID(category = "Window", id = "cz.dfi.graphs.BatteryGraphTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_BatteryGraphAction",
        preferredID = "BatteryGraphTopComponent"
)
@Messages({
    "CTL_BatteryGraphAction=BatteryGraph",
    "CTL_BatteryGraphTopComponent=BatteryGraph Window",
    "HINT_BatteryGraphTopComponent=This is a BatteryGraph window"
})
public final class BatteryGraphTopComponent extends TopComponent implements LookupListener {

    protected final JFreeChart chart;
    protected final SimpleTimeDataset dataSet;
    private final Lookup.Result<BatteryPercentWrapper> batteryResult;

    public BatteryGraphTopComponent() {
        initComponents();

        dataSet = new SimpleTimeDataset();
//        chart = ChartFactory.createXYLineChart(null,
//                "Time [sec]", "Battery [percent]", dataSet, PlotOrientation.VERTICAL, false, true,
//                false);
        chart = ChartFactory.createTimeSeriesChart(null, "Time [sec]", "Battery", dataSet, false, true, false);
        ChartPanel cp = new ChartPanel(chart);
        GraphsCommon.setupChart(chart);
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(cp);
        batteryResult = FileLookup.getDefault().lookupResult(BatteryPercentWrapper.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
     @Override
    public void componentOpened() {
        setName(Bundle.CTL_BatteryGraphTopComponent());
        setToolTipText(Bundle.HINT_BatteryGraphTopComponent());
        batteryResult.addLookupListener(this);
        resultChanged(null);
    }

    @Override
    public void componentClosed() {
        batteryResult.removeLookupListener(this);

    }

    @Override
    public void resultChanged(LookupEvent ev) {
        Collection<? extends BatteryPercentWrapper> alt = batteryResult.allInstances();
        if (alt.isEmpty()) {
            dataSet.resultChanged(new long[0], new double[0]);
        } else {
            BatteryPercentWrapper a = alt.iterator().next();
            dataSet.resultChanged(a.getTimeStamps().getOnboardValues(), a.getValuesAsDoubles());
        }
    }

}
