/*
 */
package cz.dfi.graphs;

import cz.dfi.datamodel.FlightRecordsWrapper;
import cz.dfi.recorddataprovider.caching.CachedDataProvider;
import cz.dfi.recorddataprovider.caching.CachedDataReceiver;
import java.awt.BorderLayout;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.DefaultXYDataset;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//cz.dfi.graphs//VelocityGraph//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "VelocityGraphTopComponent",
        iconBase = "cz/dfi/graphs/iconmonstr-crosshair-icon-16.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "output", openAtStartup = true)
@ActionID(category = "Window", id = "cz.dfi.graphs.VelocityGraphTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_VelocityGraphAction",
        preferredID = "VelocityGraphTopComponent"
)
@Messages({
    "CTL_VelocityGraphAction=VelocityGraph",
    "CTL_VelocityGraphTopComponent=VelocityGraph Window",
    "HINT_VelocityGraphTopComponent=This is a VelocityGraph window"
})
public final class VelocityGraphTopComponent extends TopComponent implements CachedDataReceiver<double[][]>{

    private final DefaultXYDataset dataSet;
    private final JFreeChart chart;
    private double[][] graphValues;

    public VelocityGraphTopComponent() {
        initComponents();
         setName(Bundle.CTL_VelocityGraphTopComponent());
        setToolTipText(Bundle.HINT_VelocityGraphTopComponent());
         dataSet = new DefaultXYDataset();
        chart = ChartFactory.createXYLineChart(null,
                "Time [sec]", "Distance [cm/s]", dataSet, PlotOrientation.VERTICAL, true, true,
                false);
        ChartPanel cp = new ChartPanel(chart);
        jPanel1.setLayout(new BorderLayout());
        chart.getXYPlot().setDomainPannable(true);
        chart.getXYPlot().setRangePannable(true);
        jPanel1.add(cp);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
        @Override
    public void componentOpened() {
        cachedData = CachedDataProvider.create(this);
    }
    private CachedDataProvider<double[][]> cachedData;

    @Override
    public void componentClosed() {
        cachedData.deleteData();
    }

     @Override
    public double[][] getDataForStoring(Lookup currentContext) {
        FlightRecordsWrapper r = GraphsCommon.getRecordsWrapper(currentContext);
        graphValues = r.getVelocities();
        return graphValues;
    }


    @Override
    public void setCurrentData(double[][] data) {
        graphValues = data;
        dataSet.removeSeries("vx");
        dataSet.removeSeries("vy");
        dataSet.removeSeries("vz");
        if (data != null) {
            dataSet.addSeries("Velocity in x", new double[][] {data[0],data[1]});
            dataSet.addSeries("Velocity in y", new double[][] {data[0],data[2]});
            dataSet.addSeries("Velocity in z", new double[][] {data[0],data[3]});
        }

    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
